"""fix jd csv columns

Revision ID: 2babf82da3dc
Revises: af5bd04213e2
Create Date: 2026-01-08 01:52:27.061551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2babf82da3dc'
down_revision = 'af5bd04213e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jds', schema=None) as batch_op:
        batch_op.alter_column('probability',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('billed_percent',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('identified_emp_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('original_billable_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('updated_billable_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('billing_end_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('requirement_expiry_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('resource_required_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('requirement_initiated_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('urgent',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('ctc_rate',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('aging',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sqlite.JSON(), nullable=True))
        batch_op.alter_column('aging',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('ctc_rate',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('urgent',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('requirement_initiated_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('resource_required_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('requirement_expiry_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('billing_end_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('updated_billable_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('original_billable_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('identified_emp_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('billed_percent',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('probability',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
