"""add JD table

Revision ID: 4e0ebffa89a4
Revises: d85a8f000bf0
Create Date: 2026-01-08 00:11:57.520012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4e0ebffa89a4'
down_revision = 'd85a8f000bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jds_sid'))

    op.drop_table('jds')
    op.drop_table('screening_result')
    op.drop_table('candidate')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_session_uuid'))

    op.drop_table('chat_sessions')
    op.drop_table('job_description')
    op.drop_table('candidate_project')
    op.drop_table('chat_messages')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_organization'))

    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), nullable=False),
    sa.Column('organization', sa.VARCHAR(length=200), nullable=True),
    sa.Column('start_date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('duration_months', sa.INTEGER(), nullable=True),
    sa.Column('is_academic', sa.BOOLEAN(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('all_technologies', sqlite.JSON(), nullable=True),
    sa.Column('team_size_estimate', sa.INTEGER(), nullable=True),
    sa.Column('total_contributors', sa.INTEGER(), nullable=True),
    sa.Column('impact_metrics', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_organization'), ['organization'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('responsibilities', sqlite.JSON(), nullable=True),
    sa.Column('technical_tools', sqlite.JSON(), nullable=True),
    sa.Column('contribution', sa.TEXT(), nullable=True),
    sa.Column('impact', sa.TEXT(), nullable=True),
    sa.Column('candidate_start_date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('candidate_end_date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('candidate_duration_months', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_description',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), nullable=True),
    sa.Column('min_experience_years', sa.FLOAT(), nullable=True),
    sa.Column('required_skills', sqlite.JSON(), nullable=True),
    sa.Column('bonus_skills', sqlite.JSON(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('employment_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('seniority_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('salary_min', sa.FLOAT(), nullable=True),
    sa.Column('salary_max', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_session_uuid'), ['session_uuid'], unique=1)

    op.create_table('candidate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('raw_text', sa.TEXT(), nullable=True),
    sa.Column('parsed', sqlite.JSON(), nullable=True),
    sa.Column('pdf_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=300), nullable=True),
    sa.Column('github', sa.VARCHAR(length=300), nullable=True),
    sa.Column('portfolio', sa.VARCHAR(length=300), nullable=True),
    sa.Column('total_experience_years', sa.FLOAT(), nullable=True),
    sa.Column('primary_role', sa.VARCHAR(length=200), nullable=True),
    sa.Column('primary_domain', sa.VARCHAR(length=200), nullable=True),
    sa.Column('skills', sqlite.JSON(), nullable=True),
    sa.Column('education', sqlite.JSON(), nullable=True),
    sa.Column('work_experiences', sqlite.JSON(), nullable=True),
    sa.Column('certifications', sqlite.JSON(), nullable=True),
    sa.Column('languages', sqlite.JSON(), nullable=True),
    sa.Column('projects', sqlite.JSON(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('role_bucket', sa.VARCHAR(length=20), nullable=True),
    sa.Column('on_bench', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.Column('candidate_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('stage', sa.INTEGER(), nullable=True),
    sa.Column('final_score', sa.FLOAT(), nullable=True),
    sa.Column('llm_score', sa.FLOAT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('reasoning', sa.TEXT(), nullable=True),
    sa.Column('strengths', sqlite.JSON(), nullable=True),
    sa.Column('weaknesses', sqlite.JSON(), nullable=True),
    sa.Column('recommendations', sqlite.JSON(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['job_description.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sid', sa.VARCHAR(length=20), nullable=False),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('sub_bu', sa.VARCHAR(length=100), nullable=True),
    sa.Column('account', sa.VARCHAR(length=100), nullable=True),
    sa.Column('project', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sub_practice_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('competency', sa.VARCHAR(length=100), nullable=True),
    sa.Column('designation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_description', sa.TEXT(), nullable=True),
    sa.Column('skills', sqlite.JSON(), nullable=True),
    sa.Column('billability', sa.VARCHAR(length=50), nullable=True),
    sa.Column('billing_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('probability', sa.FLOAT(), nullable=True),
    sa.Column('billed_percent', sa.FLOAT(), nullable=True),
    sa.Column('project_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('governance_category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('customer_interview', sa.VARCHAR(length=50), nullable=True),
    sa.Column('position_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('location_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('base_location_country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('base_location_city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('facility', sa.VARCHAR(length=100), nullable=True),
    sa.Column('fulfilment_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('approval_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sid_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('identified_emp_id', sa.INTEGER(), nullable=True),
    sa.Column('identified_emp_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('original_billable_date', sa.DATE(), nullable=True),
    sa.Column('updated_billable_date', sa.DATE(), nullable=True),
    sa.Column('billing_end_date', sa.DATE(), nullable=True),
    sa.Column('requirement_expiry_date', sa.DATE(), nullable=True),
    sa.Column('resource_required_date', sa.DATE(), nullable=True),
    sa.Column('requirement_initiated_date', sa.DATE(), nullable=True),
    sa.Column('month', sa.VARCHAR(length=20), nullable=True),
    sa.Column('request_initiated_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('dm', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bdm', sa.VARCHAR(length=100), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.Column('reason_for_cancel', sa.TEXT(), nullable=True),
    sa.Column('reason_for_lost', sa.TEXT(), nullable=True),
    sa.Column('replacement_employee', sa.VARCHAR(length=100), nullable=True),
    sa.Column('urgent', sa.BOOLEAN(), nullable=True),
    sa.Column('ctc_rate', sa.FLOAT(), nullable=True),
    sa.Column('customer_reference_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('billing_loss_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('aging', sa.INTEGER(), nullable=True),
    sa.Column('action_items', sa.TEXT(), nullable=True),
    sa.Column('parsed', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jds_sid'), ['sid'], unique=1)

    # ### end Alembic commands ###
