"""create jds table

Revision ID: af5bd04213e2
Revises: 4e0ebffa89a4
Create Date: 2026-01-08 01:43:12.355288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5bd04213e2'
down_revision = '4e0ebffa89a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=300), nullable=True),
    sa.Column('github', sa.String(length=300), nullable=True),
    sa.Column('portfolio', sa.String(length=300), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=True),
    sa.Column('primary_role', sa.String(length=200), nullable=True),
    sa.Column('primary_domain', sa.String(length=200), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('work_experiences', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('role_bucket', sa.String(length=20), nullable=True),
    sa.Column('on_bench', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_session_uuid'), ['session_uuid'], unique=True)

    op.create_table('jds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('sub_bu', sa.String(length=100), nullable=True),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('sub_practice_name', sa.String(length=200), nullable=True),
    sa.Column('competency', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('billability', sa.String(length=50), nullable=True),
    sa.Column('billing_type', sa.String(length=50), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('billed_percent', sa.Float(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('governance_category', sa.String(length=100), nullable=True),
    sa.Column('customer_interview', sa.String(length=50), nullable=True),
    sa.Column('position_type', sa.String(length=50), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('base_location_country', sa.String(length=100), nullable=True),
    sa.Column('base_location_city', sa.String(length=100), nullable=True),
    sa.Column('facility', sa.String(length=100), nullable=True),
    sa.Column('fulfilment_type', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('sid_status', sa.String(length=50), nullable=True),
    sa.Column('identified_emp_id', sa.Integer(), nullable=True),
    sa.Column('identified_emp_name', sa.String(length=200), nullable=True),
    sa.Column('original_billable_date', sa.Date(), nullable=True),
    sa.Column('updated_billable_date', sa.Date(), nullable=True),
    sa.Column('billing_end_date', sa.Date(), nullable=True),
    sa.Column('requirement_expiry_date', sa.Date(), nullable=True),
    sa.Column('resource_required_date', sa.Date(), nullable=True),
    sa.Column('requirement_initiated_date', sa.Date(), nullable=True),
    sa.Column('month', sa.String(length=20), nullable=True),
    sa.Column('request_initiated_by', sa.String(length=100), nullable=True),
    sa.Column('dm', sa.String(length=100), nullable=True),
    sa.Column('bdm', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('reason_for_cancel', sa.Text(), nullable=True),
    sa.Column('reason_for_lost', sa.Text(), nullable=True),
    sa.Column('replacement_employee', sa.String(length=100), nullable=True),
    sa.Column('urgent', sa.Boolean(), nullable=True),
    sa.Column('ctc_rate', sa.Float(), nullable=True),
    sa.Column('customer_reference_id', sa.String(length=100), nullable=True),
    sa.Column('billing_loss_status', sa.String(length=50), nullable=True),
    sa.Column('aging', sa.Integer(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jds_sid'), ['sid'], unique=True)

    op.create_table('job_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('min_experience_years', sa.Float(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('bonus_skills', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('is_academic', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('all_technologies', sa.JSON(), nullable=True),
    sa.Column('team_size_estimate', sa.Integer(), nullable=True),
    sa.Column('total_contributors', sa.Integer(), nullable=True),
    sa.Column('impact_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_organization'), ['organization'], unique=False)

    op.create_table('candidate_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('technical_tools', sa.JSON(), nullable=True),
    sa.Column('contribution', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('candidate_start_date', sa.String(length=50), nullable=True),
    sa.Column('candidate_end_date', sa.String(length=50), nullable=True),
    sa.Column('candidate_duration_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.String(length=64), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['job_description.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_result')
    op.drop_table('chat_messages')
    op.drop_table('candidate_project')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_organization'))
        batch_op.drop_index(batch_op.f('ix_project_name'))

    op.drop_table('project')
    op.drop_table('job_description')
    with op.batch_alter_table('jds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jds_sid'))

    op.drop_table('jds')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_session_uuid'))

    op.drop_table('chat_sessions')
    op.drop_table('candidate')
    # ### end Alembic commands ###
