"""project merge history

Revision ID: dbc6b30937ef
Revises: 9d3e2bb84283
Create Date: 2026-01-12 23:22:34.164558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc6b30937ef'
down_revision = '9d3e2bb84283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    existing_tables = set(insp.get_table_names())
    if 'project_merge_history' not in existing_tables:
        op.create_table('project_merge_history',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('source_project_id', sa.Integer(), nullable=False),
        sa.Column('target_project_id', sa.Integer(), nullable=False),
        sa.Column('source_project_before', sa.JSON(), nullable=True),
        sa.Column('target_project_before', sa.JSON(), nullable=True),
        sa.Column('moved_links', sa.JSON(), nullable=True),
        sa.Column('llm_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('reversed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['source_project_id'], ['project.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_project_id'], ['project.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )

    try:
        existing_indexes = {ix.get('name') for ix in insp.get_indexes('project_merge_history')}
    except Exception:
        existing_indexes = set()
    if 'ix_project_merge_history_source_project_id' not in existing_indexes:
        with op.batch_alter_table('project_merge_history', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_project_merge_history_source_project_id'), ['source_project_id'], unique=False)
    if 'ix_project_merge_history_target_project_id' not in existing_indexes:
        with op.batch_alter_table('project_merge_history', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_project_merge_history_target_project_id'), ['target_project_id'], unique=False)

    project_cols = {c['name'] for c in insp.get_columns('project')}
    if 'merged_into_id' not in project_cols:
        with op.batch_alter_table('project', schema=None) as batch_op:
            batch_op.add_column(sa.Column('merged_into_id', sa.Integer(), nullable=True))
    if 'merged_at' not in project_cols:
        with op.batch_alter_table('project', schema=None) as batch_op:
            batch_op.add_column(sa.Column('merged_at', sa.DateTime(), nullable=True))

    proj_indexes = {ix.get('name') for ix in insp.get_indexes('project')}
    if 'ix_project_merged_into_id' not in proj_indexes:
        with op.batch_alter_table('project', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_project_merged_into_id'), ['merged_into_id'], unique=False)

    try:
        proj_fks = {fk.get('name') for fk in insp.get_foreign_keys('project')}
    except Exception:
        proj_fks = set()
    if 'fk_project_merged_into_id_project' not in proj_fks:
        with op.batch_alter_table('project', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_project_merged_into_id_project', 'project', ['merged_into_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_merged_into_id_project', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_project_merged_into_id'))
        batch_op.drop_column('merged_at')
        batch_op.drop_column('merged_into_id')

    with op.batch_alter_table('project_merge_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_merge_history_target_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_merge_history_source_project_id'))

    op.drop_table('project_merge_history')
    # ### end Alembic commands ###
